#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newSocial.DataAcess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SocialNetWork")]
	public partial class ConLinQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConLinQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
        public ConLinQDataContext() : this("Data Source=socialmedia.c7bbmsxuypbd.us-east-1.rds.amazonaws.com,1433;Initial Catalog=SocialNetWork;User ID=admin;Password=progra12345") { }
        public ConLinQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConLinQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConLinQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.COUNT_FOLLOWERS")]
		public int COUNT_FOLLOWERS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FollowersCount", DbType="Int")] ref System.Nullable<int> followersCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, followersCount);
			followersCount = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.COUNT_FOLLOWING")]
		public int COUNT_FOLLOWING([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FollowingCount", DbType="Int")] ref System.Nullable<int> followingCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, followingCount);
			followingCount = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.COUNT_LIKES")]
		public int COUNT_LIKES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostId", DbType="Int")] System.Nullable<int> postId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LikesCount", DbType="Int")] ref System.Nullable<int> likesCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), postId, likesCount);
			likesCount = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FOLLOW_AND_UNFOLLOW")]
		public int FOLLOW_AND_UNFOLLOW([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> followerUserId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> followedUserId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), followerUserId, followedUserId, eRRORID, eRRORDESCRIPCION);
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LIKE_POST")]
		public int LIKE_POST([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> likingUserId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostID", DbType="Int")] System.Nullable<int> postID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESULT", DbType="Int")] ref System.Nullable<int> rESULT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPTION", DbType="VarChar(250)")] ref string dESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), likingUserId, postID, rESULT, dESCRIPTION);
			rESULT = ((System.Nullable<int>)(result.GetParameterValue(2)));
			dESCRIPTION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LOAD_POSTS")]
		public ISingleResult<LOAD_POSTSResult> LOAD_POSTS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> post_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), post_id, eRRORID, eRRORDESCRIPCION);
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<LOAD_POSTSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.REGISTER_USER")]
		public int REGISTER_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string users_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string last_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string u_email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string user_password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> sign_up_date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), users_name, last_name, username, u_email, user_password, sign_up_date, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SEARCH_USER")]
		public int SEARCH_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> userfound, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] ref string usernameFound, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> userID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, userfound, usernameFound, userID);
			userfound = ((System.Nullable<int>)(result.GetParameterValue(1)));
			usernameFound = ((string)(result.GetParameterValue(2)));
			userID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UPLOAD_POST")]
		public int UPLOAD_POST([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> created_by_user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string caption, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary post_image, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), created_by_user_id, caption, post_image, resultID, eRRORDESCRIPCION);
			resultID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPostsFromFollowedUsersWithLikes")]
		public ISingleResult<GetPostsFromFollowedUsersWithLikesResult> GetPostsFromFollowedUsersWithLikes([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> loggedInUserId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPTION", DbType="VarChar(250)")] ref string dESCRIPTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESULT", DbType="Int")] ref System.Nullable<int> rESULT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), loggedInUserId, dESCRIPTION, rESULT);
			dESCRIPTION = ((string)(result.GetParameterValue(1)));
			rESULT = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((ISingleResult<GetPostsFromFollowedUsersWithLikesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LOAD_USER_PROFILE")]
		public int LOAD_USER_PROFILE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(255)")] ref string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(255)")] ref string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="VarChar(255)")] ref string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FollowingCount", DbType="Int")] ref System.Nullable<int> followingCount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FollowerCount", DbType="Int")] ref System.Nullable<int> followerCount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] ref string description)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, username, name, lastName, followingCount, followerCount, result, description);
			username = ((string)(result1.GetParameterValue(1)));
			name = ((string)(result1.GetParameterValue(2)));
			lastName = ((string)(result1.GetParameterValue(3)));
			followingCount = ((System.Nullable<int>)(result1.GetParameterValue(4)));
			followerCount = ((System.Nullable<int>)(result1.GetParameterValue(5)));
			result = ((System.Nullable<int>)(result1.GetParameterValue(6)));
			description = ((string)(result1.GetParameterValue(7)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LOGIN_USER")]
		public int LOGIN_USER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string u_email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string u_password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> user_can_access, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] ref System.Nullable<int> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), u_email, u_password, user_can_access, userId);
			user_can_access = ((System.Nullable<int>)(result.GetParameterValue(2)));
			userId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LOAD_PROFILE_PICTURES")]
		public ISingleResult<LOAD_PROFILE_PICTURESResult> LOAD_PROFILE_PICTURES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESULT", DbType="VarChar(250)")] ref string rESULT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPTION", DbType="VarChar(250)")] ref string dESCRIPTION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_ID, rESULT, dESCRIPTION);
			rESULT = ((string)(result.GetParameterValue(1)));
			dESCRIPTION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<LOAD_PROFILE_PICTURESResult>)(result.ReturnValue));
		}
	}
	
	public partial class LOAD_POSTSResult
	{
		
		private int _post_id;
		
		private System.Nullable<int> _created_by_user_id;
		
		private System.DateTime _create_date;
		
		private string _caption;
		
		private System.Data.Linq.Binary _post_image;
		
		public LOAD_POSTSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_id", DbType="Int NOT NULL")]
		public int post_id
		{
			get
			{
				return this._post_id;
			}
			set
			{
				if ((this._post_id != value))
				{
					this._post_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by_user_id", DbType="Int")]
		public System.Nullable<int> created_by_user_id
		{
			get
			{
				return this._created_by_user_id;
			}
			set
			{
				if ((this._created_by_user_id != value))
				{
					this._created_by_user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="Date NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caption", DbType="VarChar(500)")]
		public string caption
		{
			get
			{
				return this._caption;
			}
			set
			{
				if ((this._caption != value))
				{
					this._caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_image", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary post_image
		{
			get
			{
				return this._post_image;
			}
			set
			{
				if ((this._post_image != value))
				{
					this._post_image = value;
				}
			}
		}
	}
	
	public partial class GetPostsFromFollowedUsersWithLikesResult
	{
		
		private int _post_id;
		
		private string _username;
		
		private System.Data.Linq.Binary _post_image;
		
		private string _caption;
		
		private System.Nullable<int> _likes_count;
		
		public GetPostsFromFollowedUsersWithLikesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_id", DbType="Int NOT NULL")]
		public int post_id
		{
			get
			{
				return this._post_id;
			}
			set
			{
				if ((this._post_id != value))
				{
					this._post_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_image", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary post_image
		{
			get
			{
				return this._post_image;
			}
			set
			{
				if ((this._post_image != value))
				{
					this._post_image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caption", DbType="VarChar(500)")]
		public string caption
		{
			get
			{
				return this._caption;
			}
			set
			{
				if ((this._caption != value))
				{
					this._caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_likes_count", DbType="Int")]
		public System.Nullable<int> likes_count
		{
			get
			{
				return this._likes_count;
			}
			set
			{
				if ((this._likes_count != value))
				{
					this._likes_count = value;
				}
			}
		}
	}
	
	public partial class LOAD_PROFILE_PICTURESResult
	{
		
		private int _id;
		
		private int _post_id;
		
		private System.Data.Linq.Binary _post_image;
		
		public LOAD_PROFILE_PICTURESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_id", DbType="Int NOT NULL")]
		public int post_id
		{
			get
			{
				return this._post_id;
			}
			set
			{
				if ((this._post_id != value))
				{
					this._post_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_image", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary post_image
		{
			get
			{
				return this._post_image;
			}
			set
			{
				if ((this._post_image != value))
				{
					this._post_image = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
